server:
  port: 0
spring:
  redis:
    host: localhost
    port: 6379

  #rabbirtMq 환경설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_order_msa
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform:  org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

    #    eureka 에 등록된 서버 id
  application:
    name: member-service
eureka:
  client:
    serviceUrl:
      #      eureka 에 서비스로 등록
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
jwt:
  expiration: 30
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: my_refresh_token_secret

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    s3:
      bucket:
